version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  csc3131-server:
    build: .
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sam
      - MONGO_INITDB_ROOT_PASSWORD=buildingsystems
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
