version: "3"
services:
  csc3131-server:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    env_file:
      - ./.env.docker
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: