version: "3"
services:
  nginx:
    ports:
      - "80:80"
  csc3131-server:
    build: 
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - DB_URI=${DB_URI}
      - DOCKER_DB_URI=${DOCKER_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    command: node server.js