version: "3"
services:
  nginx:
    ports:
      - "5000:80"
  csc3131-server:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev