version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  csc3131-server:
    build: .
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    env_file:
      - ./.env.docker
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: